import type { Metadata } from 'next';
import './globals.css';
import { RootProvider } from 'fumadocs-ui/provider/next';

export const metadata: Metadata = {
  title: 'Shadcn Registry',
  description: 'Generated by shadcn & fumadocs',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
        }}
      >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
